server/config/routes.rb
Skoole::Application.routes.draw do

    # AUTH
    
    match '/connect' => 'users#connect'
    match '/auth/:provider/callback' => 'users#callback'
    match '/authorized' => 'users#authorized'
    match '/auth/failure' => 'site#welcome'
    match '/logout' => 'users#logout'

    # SITE

    root to: 'site#welcome'
    
    resources :books
    resources :listings
    resources :buy_listings, :controller => :listings, :listing_type => 'BuyListing'
    resources :sell_listings, :controller => :listings, :listing_type => 'SellListing'
    
    resources :users
    match 'matches' => 'users#show'
    match 'poll_listings' => 'listings#poll'

    # CALLBACKS
    
    match 'twilio/sms' => 'messages#twilio_sms'
    match 'twilio/voice' => 'messages#twilio_voice'
    
    match 'sms_in' => 'messages#nexmo_sms'
    match 'email_in' => 'messages#sendgrid_email'

end

server/app/models/listing.rb
require 'api/facebook'

class Listing < ActiveRecord::Base
    scope :oldest, order('created_at ASC')
    
    has_one :match
    belongs_to :book
    belongs_to :user
    
    validates_presence_of :type, :book_id, :user_id, :price, :condition
    accepts_nested_attributes_for :book
    
    ##### CHILD CLASS NAMES
    
    @child_classes = []
    def self.inherited(child)
      @child_classes << child
      super # important!
    end
    def self.child_classes
      @child_classes
    end
 
    ##### CONDITIONS
 
    def self.conditions
        return {
            'New' => 0,
            'Good' => 1,
            'Fair' => 2
        }
    end
    
    def self.form_conditions
        return {
            'New condition' => 0,
            'Good condition' => 1,
            'Fair condition' => 2
        }
    end
 
    def condition_name
        return Listing.conditions.key(self.condition)
    end
    
    def fetch_matches

        @acceptable_listings = Listing.where("book_id = ? AND pending = ? AND network = ? AND user_id != ?
            AND type = ? AND price #{self.comparator} ? AND condition #{self.comparator} ?",
            self.book_id, false, self.network, self.user_id,
            "#{self.other_type_name}Listing", self.price, self.condition
        ).oldest
        
        @match = self.user.find_friend_match(@acceptable_listings)
        if @match.nil?
            is_friend = false
            puts "No friend match"
            return @acceptable_listings.first, is_friend
        else
            is_friend = true
            puts "Friend match found"
            puts @match
            return @match, is_friend
        end
         
    end
    
    ##### CHECK FOR MATCHES
    
    def match
        SkooleSettings.queuing ? (Delayed::Job.enqueue self) : self.perform
    end
    
    def perform
        puts "Looking for a match now..."
        self.post_now
        self.match_now
    end
    
    def post_now
        Facebook.listed(self)
    end
    
    def match_now        
        if self.type == 'BuyListing'
            buyer = self.user
            buyer_listing = self
            match_result = self.fetch_matches
            seller_listing = match_result[0]
            is_friend = match_result[1]
        else
            seller = self.user
            seller_listing = self
            match_result = self.fetch_matches
            buyer_listing = match_result[0]
            is_friend = match_result[1]
        end
        
        # unless we found a match, just quit
        unless buyer_listing && seller_listing
            puts "NO MATCH FOUND"
            return
        end
        
        #get the other user
        buyer.nil? ? buyer = buyer_listing.user : seller = seller_listing.user

        # create the match
        m = Match.create(
            buyer_id: buyer.id,
            buyer_number_id: buyer.new_number().id,
            buyer_listing_id: buyer_listing.id,
            seller_id: seller.id,
            seller_number_id: seller.new_number().id,
            seller_listing_id: seller_listing.id,
            network: self.network,
            friendly: is_friend,
            state: 0
        )
        
        if m.friendly
            puts "Friendly match! Awww..."
        end

        # try to save the match
        if !m.save() 
            puts "Error creating match: #{m.errors.inspect}"
            return
        end
            
        # mark listings as pending
        buyer_listing.pending = true
        seller_listing.pending = true
        
        if buyer_listing.save && seller_listing.save
            puts 'MATCH FOUND!'
            m.first_message
            Facebook.matched(buyer, m)
            Facebook.matched(seller, m)
        else
            puts "Error marking listings as pending: #{buyer_listing.errors.inspect}, #{seller_listing.errors.inspect}"
        end
        
    end
   
end

server/app/controllers/listings_controller.rb
class ListingsController < ApplicationController

    def index
        session[:last_request] = Time.now
        @listings = {
            Buy: {
                list: current_user.buy_listings,
                new_listing: BuyListing.new
            },
            Sell: {
                list: current_user.sell_listings,
                new_listing: SellListing.new
            }
        }
    end

    def poll
        time = Time.now
        @polling = true
        @listing = @current_user.listings.last
        if @listing && @listing.created_at < session[:last_request] then @listing = nil end
        session[:last_request] = time
        render 'create'
    end

    def create
        puts params.inspect
        
        if @book = Book.via_isbn(params[:isbn])
            @listing = @book.buy_listings.create(params[:buy_listing]) if params[:buy_listing]
            @listing = @book.sell_listings.create(params[:sell_listing]) if params[:sell_listing]
        end
        session[:last_request] = Time.now
        if @book.nil?
            puts "No book found for this ISBN."
        end
        if @listing.nil?
            puts "No listing found for this book."
        else
            @listing.match
        end
    end
    
    def destroy
        @listing = Listing.find(params[:id])
        @listing.destroy
    end
  
end

server/app/views/listings/_book.html.erb
<%= builder.label :isbn %>
<%= builder.text_field :isbn %>

server/app/views/listings/_form.html.erb
<div class="overlay"><div id="book-form" class="lightbox">

	<div class="lightbox-title">
		<div class="exit">X</div>
		<h2>Add a Book to <%= listing.type_name %></h2>
	</div>
	
	<div class="lightbox-content">
		<%= form_for listing, url: listings_path, remote: true, :html => { class: "new_listing_form"} do |f| %>

		<div class="field-box isbn-field">
			<input autocomplete="off" class="isbn-text-field empty" id="<%= "#{listing.type_name.downcase}-isbn" %>" name="isbn" type="text" value="">
		</div>
		
		<ul id="<%= "#{listing.type_name.downcase}-matched-books" %>" style="display: none;"></ul>

		<div class="field-box price-field">
			<%= f.label :price, '$' %>
			<%= f.number_field :price %>
		</div>
		
		<div class="field-box conditions-field">
			<div class="arrow-down"></div>
			<%= f.select :condition, options_for_select(Listing.form_conditions) %>
		</div>

		<div class="clear"></div>
		<%= f.hidden_field :user_id, value: @current_user.id %>
		<%= f.hidden_field :network, value: @current_user.network %>
		<%= f.submit 'List' %>

		<% end %>
		<div class="clear"></div>
	</div>
	
</div></div>

server/app/views/listings/_index.html.erb
<div id="bin" class="listings">

	<!-- HEADER -->

	<div class="header">
		<div id="about">
			<div class="page">
		
				<!-- TAGLINE -->
		
				<div id="left-content">
					<h1>List your books</h1>
		    	</div>

				<!-- BUTTON -->

		    	<div id="right-content">
					<!--Auto Matching-->
				</div>
		
				<div class="clear"></div>
			</div>
		</div>
	</div>

	<!-- LISTS -->

	<div id="lists-container" class="main-content">
		<div id="lists">
			<div class="page">
	
				<% @listings.each do |kind_name, kind| %>
	
				<div id="<%= kind_name %>Listing" class="section">
					<div>
						<div class="add">+</div>
						<%= render "form", listing: kind[:new_listing] %>
					</div>
			
					<h1><%= kind_name %>ing (<span class="count"><%= kind[:list].count %></span>)</h1>
					<div class="list" id="listBuy">
						<% for @listing in kind[:list] do %>
						<%= render "listing" %>
						<% end %>
					</div>
				</div>
		
				<% end %>
	
			</div>
		</div>
	</div>

</div>

server/app/views/listings/_listing.html.erb
<div class="listing" id="listing-<%= @listing.id %>">
	<%= image_tag @listing.book.thumbnail, class: 'thumbnail' %>
	<div class="info">
		<h2><%= @listing.book.title.titleize %></h2>
		<div class="attributes"><%= @listing.type == 'BuyListing' ? 'Up to' : 'For' %> $<%= @listing.price %>.00, in <%= @listing.condition_name %> condition</div>
		<div class="status">
			<% if @listing.pending == true %>
				<%= image_tag('matched.png') %>
				Matched
			<% else %>
				<%= image_tag('reload.png') %>
				Searching for matches...
			<% end %>
		</div>
		<div class="edit-book"><%= image_tag('edit-22.png') %></div>
		<%= link_to(@listing, url_options = { method: :delete, remote: true, confirm: 'Are you sure you want to remove this book from your list? Pending matches will be canceled.', class: 'destroy' }) do %>
			<%= image_tag('trash-22.png') %>
		<% end %>
	</div>
</div>

server/app/views/listings/create.js.erb
<% if @listing %>
$('<%= escape_javascript(render "listing")%>').hide().appendTo('#<%= @listing.type %> .list').fadeIn();
update_counts()
<% elsif @polling == false %>
alert('Book could not be found')
<% end %>

server/app/views/listings/destroy.js.erb
$('#listing-<%= @listing.id %>').animate({ height: 'toggle', opacity: 'toggle' }, 300, function() {
	$(this).remove()
	update_counts()
})

server/app/views/listings/index.js.erb
document.location.hash = 'lists'
<%= render 'application/navbar' %>
$('#main').html('<%= escape_javascript(render "index")%>')
clear_forms()