server/config/routes.rb
Skoole::Application.routes.draw do

    # AUTH
    
    match '/connect' => 'users#connect'
    match '/auth/:provider/callback' => 'users#callback'
    match '/authorized' => 'users#authorized'
    match '/auth/failure' => 'site#welcome'
    match '/logout' => 'users#logout'

    # SITE

    root to: 'site#welcome'
    
    resources :books
    resources :listings
    resources :buy_listings, :controller => :listings, :listing_type => 'BuyListing'
    resources :sell_listings, :controller => :listings, :listing_type => 'SellListing'
    
    resources :users
    match 'matches' => 'users#show'
    match 'poll_listings' => 'listings#poll'

    # CALLBACKS
    
    match 'twilio/sms' => 'messages#twilio_sms'
    match 'twilio/voice' => 'messages#twilio_voice'
    
    match 'sms_in' => 'messages#nexmo_sms'
    match 'email_in' => 'messages#sendgrid_email'

end

server/app/models/book.rb
require 'api/googlebooks'

class Book < ActiveRecord::Base
    
    has_many :listings
    has_many :buy_listings
    has_many :sell_listings
    
    validates_presence_of :isbn
    attr_accessible :isbn, :author, :title, :published, :thumbnail
    
    def self.via_isbn(isbn)
        book = self.find_by_isbn(isbn)
        if book.nil? then book = GoogleBooks.book_for_isbn(isbn) end
        return book
    end
    
end

server/app/controllers/books_controller.rb
class BooksController < ApplicationController
    layout false, :only => :your_action_name 
   
    def show
        if params[:fb_action_ids]
            redirect_to root_url
        end
        @book = Book.find(params[:id])
    end
    
end

server/app/views/books/show.html.erb
<html>

<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# skooledev: http://ogp.me/ns/fb/skooledev#">
    <meta property="fb:app_id"		content="143680292405619" />
    <meta property="og:type"		content="skooledev:book" />
    <meta property="og:url"			content="<%= book_url(@book) %>" />
    <meta property="og:title"		content="<%= @book.title.titleize %>" />
	<meta property="skooledev:author"		content="<%= @book.author.titleize %>" />
    <meta property="og:description"	content="Listed on Skoole.com" />
    <meta property="og:image"		content="<%= @book.thumbnail %>" />
</head>

<body>
</body>

</html>